### ISSUE TITLE
jQuery.scrollTo stopped working from Chrome 61

### ISSUE THREAD

**Issue by hchalla** [flesler/jquery.scrollTo#164] opened 2017-09-27 07:07 UTC
It works fine in Chrome 60 and other browsers. We are using jquery-1.7.2 and jquery.scrollTo-1.4.2. Please let us know the workaround from Chrome 61. Thanks

**Comment by OrazioLentini** [comment] 2017-09-27 13:51
@hchalla I had the same issue with version 1.4.2. I updated to the latest jquery.ScrollTo (version 2.1.2) and the it works again on chrome.

**Comment by hchalla** [comment] 2017-09-27 13:59
Hi,

Thank you for your reply.

Which version of jQuery do you have?

Thanks
Harshini

**Comment by alexandre-stimpfling** [comment] 2017-09-27 16:06
Hi,

Thanks @OrazioLentini !
Same problem today after Chrome update to 61 version but i confirm that the update to the latest version of jQuery.scrollTo (2.1.2) works very good. For informations, i use Jquery 1.11.0.

**Comment by hchalla** [comment] 2017-09-28 04:00
I tried using jQuery 1.11.0 and jQuery.scrollTo(2.1.2) but it doesn't work
correctly. Earlier we had the scrollTo call on document.ready(), so the
page would scroll to the right div. But now (after updating jQuery and
jQuery.scrollTo) it scrolls to the right div and then continues to the
point I was on the page when I refreshed the page. When I add the scrollTo
on window.load90, the page scrolls to where I was at the time of refresh
and then goes to the right div. Is this how it works for you?

Thanks
Harshini

*Time zone: BST+4.5 hrs*

**Comment by alexandre-stimpfling** [comment] 2017-09-28 07:40
Hi,
I just tested to call scrollTo on document.ready () and window.load, I have the same reaction you specify. I do not use scrollTo this way on my sites, it activates after clicking on an item and so I do not have these problems. Not being a javascript specialist, I can not help you anymore. :wink:

**Comment by JamoCA** [comment] 2017-09-29 22:04
Use **setTimeout()**.

If I add a timeout of 100ms, the scrollTo library works using load/onReady listeners with Chrome 62.

    setTimeout(function(){
        $(window).scrollTo('#myDiv');
    }, 100);

I recommend using Ben Alman's **[doTimeOut()](http://benalman.com/projects/jquery-dotimeout-plugin/)** if you want to cancel, override or desire to chain functions.

    $.doTimeout('someid', 100, function(){
        $(window).scrollTo('#myDiv');
    });

**Comment by jtara** [comment] 2017-10-01 19:27
Ancient script versions shouldn't be expected to work with current browsers. Because developers don't have the gift of precognition.

Both jquery.scrollTo 1.4.2 and jQuery 1.7.2 are long obsolete, and not supported for current browsers. ditto jQuery 1.11.0.

**Comment by dirface** [comment] 2017-10-17 14:53
Or:

`$('a[href^="#"]').on('click', function(event) {
    var target = $(this.getAttribute('href'));
    if( target.length ) {
        event.preventDefault();
        $('html, body').stop().animate({
            scrollTop: target.offset().top
        }, 1000);
    }
});`

**Comment by arquadrado** [comment] 2018-03-02 16:04
I have this problem in Chrome Version 62.0.3202.89, with scrollTo v 2.1.2 and Jquery 3.2.1. It simple does nothing. 

```$("#list-news").animate({
            scrollTop: $("#list-element").offset().top
        }, 2000);```

This also doesn't work. Any thoughts? 

Thanks!

**Comment by flesler** [comment] 2018-03-02 17:50
@arquadrado that's not using scrollTo. Try giving #list-news `overflow: auto`. It it doesn't show scrollbars of its own, it's surely an HTML/CSS problem

**Comment by bendis** [comment] 2018-03-12 11:38
I had this problem in Chrome (both OSX and WIN) with obsolete versions of scrollTo 1.4.3.1 and jQuery 1.7.1. Updating scrollTo to 2.1.2 and jQuery 1.8.3 (still obsolete :D), solved me the problem.

**Comment by paulrayrussell** [comment] 2018-03-15 16:18
I can confirm that updating both LocalScroll and ScrollTo to latest versions does fix this.

**Comment by flesler** [comment] 2018-03-15 16:58
Ok, I'm going to finally close this :)

**Closed by flesler** 2018-03-15 16:58 UTC

**Comment by anonym24** [comment] 2018-03-31 17:07
though those old versions works ok for localhost, but for online sites or if opening index.html in google chrome it doesn't work

**Comment by flesler** [comment] 2018-04-02 14:02
They are old versions for a reason, upgrade to the latest one to avoid having issues

**Comment by Allie1138** [comment] 2018-07-03 19:28
Hello... I have a site using the Brushed html5 template. Scroll stopped working since Chrome update. Can anyone help me with which script will work?
Hope to hear from someone soon. thx so much!

**Comment by flesler** [comment] 2018-07-03 20:38
Hi, for this kind of request you should rather ask on sites like StackOverflow, you'll get a much larger reach there

**Comment by Allie1138** [comment] 2018-07-03 21:57
Thank you for your reply!!! I'll try there! :)

**Comment by ditikrushna** [comment] 2018-10-21 11:31
Need Help !
This  code is  not working any thought .

        $("#scrollIcon").click(function(e) {      
            e.preventDefault();         
            $.scrollTo($("#about"), 1000);
});
