### ISSUE TITLE
Tween

### ISSUE THREAD

**Issue by KarelWintersky** [flesler/jquery.scrollTo#171] opened 2018-10-16 10:44 UTC
What is $.tween here:

```
$.Tween.propHooks.
```
?

I recieve 
```
6ec5ee48e1fc949f4b162af8ee98951f.js:368 Uncaught TypeError: Cannot read property 'propHooks' of undefined
    at 6ec5ee48e1fc949f4b162af8ee98951f.js:368
    at 6ec5ee48e1fc949f4b162af8ee98951f.js:368
    at 6ec5ee48e1fc949f4b162af8ee98951f.js:368
```

**Comment by KarelWintersky** [comment] 2018-10-16 16:05
1.7.2

**Comment by flesler** [comment] 2018-10-16 16:32
Here you can see the requirement: https://github.com/flesler/jquery.scrollTo/blob/master/package.json#L8

**Comment by flesler** [comment] 2018-10-17 13:53
I'm closing this since it seems like it's not a bug

**Closed by flesler** 2018-10-17 13:53 UTC
