### ISSUE TITLE
Problem with IE when page direction is right to left

### ISSUE THREAD

**Issue by MoonMonster123** [flesler/jquery.scrollTo#140] opened 2016-07-19 05:42 UTC
There seems to be an issue when using IE and when the page direction is right to left ("rtl") - it does not scroll to the correct location on the page.

In my project I set dir="rtl" so that the user can view the page in Arabic (text is also internationalized)

Steps to reproduce:
1 - Open IE 10 or IE Edge
2 - Go to the scroll to website demo http://demos.flesler.com/jquery/scrollTo
3 - Press F12 to open the developer bar
4 - Use the "DOM Explorer" to add the attribute dir="rtl" into the HTML element
5 - Try use the demo scroll to functions on the page e.g. "JQuery object"

**Comment by flesler** [comment] 2016-07-19 14:30
Hi, as I usually reply to this kind of reports. The plugin wraps $().animate() and employs $().offset(), both built into jQuery. The way to fix this is getting it fixed on jQuery (I'm guessing $().offset()).

I'd advice you to reproduce the issue just by using those and report it on jQuery. If you aren't using the latest version, you could try upgrading first, maybe that was fixed.

**Comment by KingSora** [comment] 2017-04-26 13:51
This bug exists because alls browser engines are handling "rtl scrolling" differently.
Execute this line :

```javascript
$('#pane-target').css('direction', 'rtl').scrollTo({ left : 100, top : 0 }, 800);
```  
at your demo page in different browsers and notice the difference.

**Comment by flesler** [comment] 2018-04-26 23:13
Does this also happen when using native $().animate() ?

**Closed** 2018-06-07 13:53 UTC
